#!/bin/bash
#
# cirrus-init  Execute Bash curled from AWS user-data.
#
# chkconfig:   2345 13 13
# description: Execute Bash curled from AWS user-data.

### BEGIN INIT INFO
# Provides:          $cirrus_init
# Required-Start:    $network $syslog
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Execute Bash curled from AWS user-data.
# Description:       Execute Bash curled from AWS user-data.
### END INIT INFO

# Return values according to LSB for all commands but status:
# 0       - success
# 1       - generic or unspecified error
# 2       - invalid or excess argument(s)
# 3       - unimplemented feature (e.g. "reload")
# 4       - user had insufficient privileges
# 5       - program is not installed
# 6       - program is not configured
# 7       - program is not running
# 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)

. /etc/rc.d/init.d/functions

exec 2> >(logger -p daemon.err -t cirrus-init)

RETVAL=0
userdata_url='http://169.254.169.254/latest/user-data'

start() {
  userdata="$(curl --silent --connect-timeout 3 $userdata_url)"
  if echo "$userdata" | head --lines 1 | grep --quiet '#!/bin/bash' ; then
    /bin/bash -c "$userdata"
    RETVAL=$?
    if [ $RETVAL -gt 0 ] ; then
      failure
    else
      success
    fi
    echo $"Executing bash user-data: "
  else
    success
    echo $"No bash user-data: "
    RETVAL=0
  fi
}

status() {
  curl --connect-timeout 3 "$userdata_url"
  RETVAL=0
}

stop() {
  # no-op
  RETVAL=7
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|try-restart|condrestart)
    start
  ;;
  reload|force-reload)
    start
  ;;
  status)
    status
  ;;
  *)
    echo $"Usage: $0 {start|stop|status|try-restart|condrestart|restart|force-reload|reload}"
    RETVAL=2
  ;;
esac

exit $RETVAL
